# Generated by Django 4.0.5 on 2022-07-06 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discharge', '0003_alter_data_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='Dischargeddata',
        ),
    ]
