# Generated by Django 4.0.5 on 2022-06-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email address')),
                ('hospital_name', models.CharField(blank=True, max_length=60)),
                ('unit_name', models.CharField(blank=True, max_length=60)),
                ('local_government', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
