# Generated by Django 4.0.5 on 2022-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morbidity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morbiditydata',
            name='user_time',
            field=models.DateField(default=''),
        ),
    ]
