# Generated by Django 4.0.5 on 2022-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morbidity', '0002_alter_morbiditydata_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morbiditydata',
            name='user_time',
            field=models.DateTimeField(default=''),
        ),
    ]
